export const FETCH_QUESTIONARE_TITLES = 'FETCH_QUESTIONARE_TITLES'
export const FETCH_QUESTIONARE_TITLES_ERROR = 'FETCH_QUESTIONARE_TITLES_ERROR'
export const FETCH_TEST_ID = 'FETCH_TEST_ID'

export const FETCH_ACTIVE_QUESTIONARE_TITLE_AND_QUESTIONS = 'FETCH_ACTIVE_QUESTIONARE_TITLE_AND_QUESTIONS'
export const RETRY_HANDLER = 'RETRY_HANDLER'
export const REPEAT_HANDLER = 'REPEAT_HANDLER'
export const ANSWER = 'ANSWER'
export const DELETE_QUESTIONARE = 'DELETE_QUESTIONARE'


export const IS_QUESTIONNAIRE_FINISHED = 'IS_QUESTIONNAIRE_FINISHED'
export const NEXT_QUESTION = 'NEXT_QUESTION'
export const QUESTION = 'QUESTION'
export const CREATE_QUIZ  = 'CREATE_QUIZ'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const GUEST_SCREEN_OFF = 'GUEST_SCREEN_OFF'
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
